### ISSUE TITLE
Support Python 2.7

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/python-libprio#2]
The build process currently only supports Python 3. It can be modified to support Python 2 too. 

It seems like SWIG is mostly independent of the language. There might be some type-mappings in the SWIG interface files that are version specific, like the ones that handle string and bytestring inter-op with C.

**Comment by wlach** [comment]
I think we should just close this. Any objections?

**Comment by acmiyaguchi** [comment]
Python 2.7 is EOL at the end of the year, so no objections.
