### ISSUE TITLE
installation steps don't work

### ISSUE THREAD

**Issue by wlach** [mozilla/python-libprio#34]
Using the recommended instructions in the README (`docker build -t prio .`), things seem to work fine for a while until...

```
...
  Downloading https://files.pythonhosted.org/packages/e3/d9/d9c56deb483c4d3289a00b12046e41428be64e8236fa210111a1f57cc42d/virtualenv_clone-0.5.1-py2.py3-none-any.whl
Installing collected packages: virtualenv, enum34, typing, certifi, virtualenv-clone, pipenv
Successfully installed certifi-2019.3.9 enum34-1.1.6 pipenv-2018.11.26 typing-3.6.6 virtualenv-16.4.3 virtualenv-clone-0.5.1
Removing intermediate container 1ed0d90316a5
 ---> 36988accc720
Step 8/13 : ENV PATH="$PATH:~/.local/bin"
 ---> Running in bf77f7a13f09
Removing intermediate container bf77f7a13f09
 ---> 5bd06bb8c8ce
Step 9/13 : WORKDIR /app
 ---> Running in 8fa3943d5ed3
Removing intermediate container 8fa3943d5ed3
 ---> b381387375f0
Step 10/13 : ADD . /app
 ---> 2809c4cd10cb
Step 11/13 : RUN make
 ---> Running in 0a9b6988ec3c
cd libprio && CCFLAGS='-fPIC' scons && cd ..

scons: *** No SConstruct file found.
File "/usr/lib/python2.7/site-packages/SCons/Script/Main.py", line 924, in _main
make: *** [Makefile:2: all] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2
```

@acmiyaguchi -- did you forget to add something to the repository? Also this would be a good excuse to make CI work. :) Currently circle is saying there are no builds.

**Comment by acmiyaguchi** [comment]
Everything necessary to build and run the project should be checked in -- something must have changed in the last few months that broke the current workflow. Things could have changed since I moved the repo from acmiyaguchi/python-libprio into mozilla/python-libprio.

**Comment by acmiyaguchi** [comment]
The answer is much simpler, the submodule isn't initialized in your repository. I'll add something to the readme to this effect.

```git submodule update --init --recursive```
